tangara_administration_homepage:
    pattern:  /
    defaults: { _controller: TangaraAdministrationBundle:Default:index }
    
tangara_administration_data:
    pattern:  /data
    defaults: { _controller: TangaraAdministrationBundle:Default:data }

tangara_administration_locale:
    pattern:  /locale
    defaults: { _controller: TangaraAdministrationBundle:Default:locale }
    
tangara_administration_files:
    pattern:  /files
    defaults: { _controller: TangaraAdministrationBundle:Default:getFiles }