tangara_administration_homepage:
    pattern:  /
    defaults: { _controller: TangaraAdministrationBundle:Default:index }

tangara_administration_locale:
    pattern:  /locale
    defaults: { _controller: TangaraAdministrationBundle:Default:locale }
    
tangara_administration_gettgr:
    pattern:  /tgr
    defaults: { _controller: TangaraAdministrationBundle:Default:getTgr }
