tangara_administration_homepage:
    pattern:  /
    defaults: { _controller: TangaraAdministrationBundle:Default:index }
    
tangara_administration_data:
    pattern:  /data
    defaults: { _controller: TangaraAdministrationBundle:Default:data }
