parameters:
#    tangara_administration.example.class: Tangara\AdministrationBundle\Example

services:
#    tangara_administration.example:
#        class: %tangara_administration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
