tangara_tangara_homepage:
    pattern:  /
    defaults: { _controller: TangaraTangaraBundle:Default:index }

#tangara_tangara_locale:
#    pattern:  /locale
#    defaults: { _controller: TangaraAdministrationBundle:Default:locale }
#
#tangara_tangara_gettgr:
#    pattern:  /tgr
#    defaults: { _controller: TangaraAdministrationBundle:Default:getTgr }

tangara_project_index:
    pattern:  /
    defaults: { _controller: TangaraTangaraBundle:Project:index }

tangara_project_show:            
    pattern:  /show/{id}
    defaults: { _controller: TangaraTangaraBundle:Project:show }
    requirements:
        id:  \d+
    
tangara_project_new:
    pattern:  /new
    defaults: { _controller: TangaraTangaraBundle:Project:new }

tangara_project_list:
    pattern:  /list
    defaults: { _controller: TangaraTangaraBundle:Project:list }

tangara_project_upload:
    pattern:  /upload/{id}
    defaults: { _controller: TangaraTangaraBundle:Project:upload }
    requirements:
        id:  \d+
        
tangara_project_up:
    pattern:  /ud
    defaults: { _controller: TangaraTangaraBundle:Project:up }

tangara_project_edit:
    pattern:  /edit/{id}
    defaults: { _controller: TangaraTangaraBundle:Project:edit }
    requirements:
        id:  \d+

tangara_project_create:
    pattern:  /create
    defaults: { _controller: TangaraTangaraBundle:Project:create}

tangara_project_files:
    pattern:  /files
    defaults: { _controller: TangaraProjectBundle:File:getFiles }

tangara_project_tgr_content:
    pattern:  /content
    defaults: { _controller: TangaraProjectBundle:File:getContent }
    
tangara_project_ajax:
    pattern:  /ajax
    defaults: { _controller: TangaraTangaraBundle:Project:getAjax}
 
# join group confirmation
tangara_project_confirmation:
    pattern:  /confirmation
    defaults: { _controller: TangaraTangaraBundle:Project:confirmation }

