parameters:
#    tangara_tangara.example.class: Tangara\TangaraBundle\Example

services:
#    tangara_tangara.example:
#        class: %tangara_tangara.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
