#parameters:
#    tangara_tangara.example.class: Tangara\TangaraBundle\Example

#services:
#    tangara_tangara.example:
#        class: %tangara_tangara.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    tangara.uploader.class: Tangara\TangaraBundle\Uploader\Uploader
    tangara.uploader.directory: C:\tangara
    tangara.uploader.tangarajs.directory: C:\tangarajs
    
services:
    tangara.uploader:
        class: "%tangara.uploader.class%"
        arguments: ["%tangara.uploader.directory%"]