tangara_tangara_main:
    resource: "@TangaraCoreBundle/Resources/config/main_routing.yml"
    prefix:   /
    
tangara_tangara_project:
    resource: "@TangaraCoreBundle/Resources/config/project_routing.yml"
    prefix:   /
    
tangara_tangara_group:
    resource: "@TangaraCoreBundle/Resources/config/group_routing.yml"
    prefix:   /

fos_user_profile:
    resource: "@TangaraCoreBundle/Resources/config/profile.xml"
    prefix: /profile
    
############################### FOS/UserBundle routing############################
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
