tangara_tangara:
    resource: "@TangaraTangaraBundle/Resources/config/routing.yml"
    prefix:   /

tangara_admin:
    resource: "@TangaraTangaraBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

#tangara_files:
#    resource: "@TangaraProjectBundle/Resources/config/routing_files.yml"
#    prefix:   /project

tangara_project:
    resource: "@TangaraTangaraBundle/Resources/config/routing_project.yml"
    prefix:   /project

#tangara_editor:
#    resource: "@TangaraEditorBundle/Resources/config/routing.yml"
#    prefix:   /editor
#
#tangara_paint:
#    resource: "@TangarawPaintBundle/Resources/config/routing.yml"
#    prefix:   /paint

# Tangara Bundles router configuration

#tangara_user:
#    resource: "@TangaraUserBundle/Resources/config/routing.yml"
#    prefix:   /

fos_user:
    resource: "@TangaraUserBundle/Resources/config/routing.yml"
    prefix: /
