tangara_step_show:
    path:  /show/{courseId}/{stepId}
    defaults: { _controller: TangaraCoreBundle:Step:show}        

tangara_step_list:
    path:  /list/{courseId}
    defaults: { _controller: TangaraCoreBundle:Step:list}

tangara_step_pick:
    path:  /pick/{courseId}/{stepId}
    defaults: { _controller: TangaraCoreBundle:Step:pick}

tangara_step_edit:
    path:  /edit/{courseId}/{stepId}
    defaults: { _controller: TangaraCoreBundle:Step:edit}

tangara_step_select:
    path:  /select/{courseId}/{stepId}
    defaults: { _controller: TangaraCoreBundle:Step:select}
    requirements:
        selectId:  \d+

tangara_step_create:
    path: /create/{courseId}
    defaults: { _controller: TangaraCoreBundle:Step:create}

tangara_step_remove:
    path: /remove/{courseId}/{stepId}
    defaults: { _controller: TangaraCoreBundle:Step:remove}

tangara_step_delete:
    path: /delete/{courseId}/{stepId}
    defaults: { _controller: TangaraCoreBundle:Step:delete}
