#showAction: info about the user and the group projects  
tangara_project_show:
    path:  /show/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:show, projectId: false }        

tangara_project_list:
    path:  /list
    defaults: { _controller: TangaraCoreBundle:Project:list }

tangara_project_edit:
    path:  /edit/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:edit, projectId: false }

tangara_project_select:
    path:  /select/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:select}
    requirements:
        projectId:  \d+

tangara_project_create:
    path: /create
    defaults: { _controller: TangaraCoreBundle:Project:create}

tangara_project_published:
    path:  /published
    defaults: { _controller: TangaraCoreBundle:Project:published}

tangara_project_execute:
    path:  /execute/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:execute, projectId: false}

tangara_project_member:
    path:  /member/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:member, projectId: false}
    
tangara_project_search_member:
    path:  /search
    defaults: { _controller: TangaraCoreBundle:Project:search_member}
    
tangara_project_add_member:
    path:  /add_member/{user}/{project}
    defaults: { _controller: TangaraCoreBundle:Project:add_member, user: false, project: false}
    
tangara_project_get_member:
    path:  /get_member/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:get_member, user: false}
    
tangara_project_add_member_ajax:
    path:  /add_member_ajax
    defaults : { _controller: TangaraCoreBundle:Project:add_member_ajax}