#routing for AdminController
tangara_admin_index:
    path:  /index
    defaults: { _controller: TangaraCoreBundle:Admin:index }
    
tangara_admin_users:
    path:  /users
    defaults: { _controller: TangaraCoreBundle:Admin:users }
    
tangara_admin_users_ajax:
    path:  /users_ajax
    defaults: { _controller: TangaraCoreBundle:Admin:users_ajax }
    
tangara_admin_projects:
    path:  /projects
    defaults: { _controller: TangaraCoreBundle:Admin:projects }
    
tangara_admin_searchUser:
    path:  /search
    defaults: { _controller: TangaraCoreBundle:Admin:searchUser }
    
tangara_admin_search_ajax:
    path:  /search_ajax
    defaults: { _controller: TangaraCoreBundle:Admin:search_ajax }
 
tangara_admin_projects_ajax:
    path:  /search_project
    defaults: { _controller: TangaraCoreBundle:Admin:projects_ajax }
    
tangara_admin_search_project:
    path:  /search_project_ajax
    defaults: { _controller: TangaraCoreBundle:Admin:search_project_ajax } 