tangara_admin_homepage:
    pattern: /
    defaults: { _controller: TangaraCoreBundle:Admin:index }

tangara_admin_users:
    pattern: /users
    defaults: { _controller: TangaraCoreBundle:Admin:users }