tangara_core_homepage:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Default:index }
    
# join group confirmation
tangara_project_confirmation:
    pattern:  /confirmation
    defaults: { _controller: TangaraCoreBundle:Default:confirmation }

tangara_test:
    pattern:  /project/test/{id}
    defaults: { _controller: TangaraCoreBundle:File:test }
    requirements:
        id:  \d+