tangara_tangara_homepage:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Default:index }
    

tangara_project_ajax:
    pattern:  /ajax
    defaults: { _controller: TangaraCoreBundle:Default:ajax }

tangara_project_ajax_test:
    pattern:  /ajax/test
    defaults: { _controller: TangaraCoreBundle:File:removeFile }
    
    
    
tangara_project_lol:
    pattern:  /lol
    defaults: { _controller: TangaraCoreBundle:Default:translation }
    

    
    
    
   
