tangara_admin_homepage:
    path: /
    defaults: { _controller: TangaraCoreBundle:Admin:index }

tangara_admin_users:
    path: /users
    defaults: { _controller: TangaraCoreBundle:Admin:users }
    
tangara_admin_update:
    path: /updateproject/{projectId}
    defaults: { _controller: TangaraCoreBundle:Admin:updateProject }