fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
    

    
    
# user ask to join a group
tangara_user_joinGroup:
    pattern:  /join_group
    defaults: { _controller: TangaraCoreBundle:Profile:askJoinGroup }
    
fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: TangaraCoreBundle:Profile:profile }

tangara_user_delete:
    pattern:  /delete_account
    defaults: { _controller: TangaraCoreBundle:Profile:delAccount }