fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

tangara_user_register:
    path: /register
    defaults: { _controller: TangaraCoreBundle:Profile:register }   

tangara_user_registration_confirmed:
    path: /registration_confirmed
    defaults: { _controller: TangaraCoreBundle:Profile:registrationConfirmed }   

tangara_user_change_password:
    path: /change-password
    defaults: { _controller: TangaraCoreBundle:Profile:changePassword}       

tangara_user_logout:
    path: /tlogout
    defaults: { _controller: TangaraCoreBundle:Profile:logout }
    
# user ask to join a group
tangara_user_joinGroup:
    path:  /join_group
    defaults: { _controller: TangaraCoreBundle:Profile:askJoinGroup }
    
tangara_user_profile_show:
    path:  /profile/{user_id}
    defaults: { _controller: TangaraCoreBundle:Profile:profile, user_id: false }

tangara_user_delete:
    path:  /delete_account
    defaults: { _controller: TangaraCoreBundle:Profile:delAccount }
    
tangara_core_user_menu:
    path:  /user_menu
    defaults: { _controller: TangaraCoreBundle:Profile:menu }
