#tangara_tangarajs_index:
#    pattern:  /
#    defaults: { _controller: TangaraCoreBundle:Project:index }

tangara_tangarajs_get_tangara_files:            
    path:  /getprograms
    defaults: { _controller: TangaraCoreBundle:File:getPrograms }

tangara_tangarajs_get_resources:            
    path:  /getresources
    defaults: { _controller: TangaraCoreBundle:File:getResources }

tangara_tangarajs_get_program_code:
    path:  /getcode
    defaults: { _controller: TangaraCoreBundle:File:getProgramCode }

tangara_tangarajs_get_program_statements:
    path:  /getstatements
    defaults: { _controller: TangaraCoreBundle:File:getProgramStatements }

tangara_tangarajs_set_program_content:
    path:  /setprogramcontent
    defaults: { _controller: TangaraCoreBundle:File:setProgramContent }

tangara_tangarajs_remove_program:
    path:  /removeprogram
    defaults: { _controller: TangaraCoreBundle:File:removeProgram }

tangara_tangarajs_remove_resource:
    path:  /removeresource
    defaults: { _controller: TangaraCoreBundle:File:removeResource }
   
tangara_tangarajs_get_resource:
    path:  /getresource/{version}/{name}
    defaults: { _controller: TangaraCoreBundle:File:getResource }

tangara_tangarajs_create_program:
    path:  /createprogram
    defaults: { _controller: TangaraCoreBundle:File:createProgram }

tangara_tangarajs_add_resource:
    path:  /addresource
    defaults: { _controller: TangaraCoreBundle:File:addResource }

tangara_tangarajs_rename_program:
    path:  /renameprogram
    defaults: { _controller: TangaraCoreBundle:File:renameProgram }

tangara_tangarajs_rename_resource:
    path:  /renameresource
    defaults: { _controller: TangaraCoreBundle:File:renameResource }

tangara_tangarajs_set_resource:
    path:  /setresource
    defaults: { _controller: TangaraCoreBundle:File:setResourceContent }

tangara_tangarajs_duplicate_resource:
    path:  /duplicateresource
    defaults: { _controller: TangaraCoreBundle:File:duplicateResource }

tangara_tangarajs_create_resource:
    path:  /createresource
    defaults: { _controller: TangaraCoreBundle:File:createResource }
