tangara_project_index:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Project:index }

#showAction: information about the project
tangara_project_show:            
    pattern:  /show/{cat}/{id}
    defaults: { _controller: TangaraCoreBundle:Project:show }
    requirements:
        id:  \d+

#newAction: create a new project for user
tangara_project_user_new:
    pattern:  /profil/{user_id}/new
    defaults: { _controller: TangaraCoreBundle:Project:new, user_id: 0, group_id: 0 }

#newAction: create a new project for group
tangara_project_group_new:
    pattern:  /group/{group_id}/new
    defaults: { _controller: TangaraCoreBundle:Project:new, user_id: 0, group_id: 0}


tangara_project_list:
    pattern:  /list
    defaults: { _controller: TangaraCoreBundle:Project:list }

tangara_project_upload:
    pattern:  /upload/{id}
    defaults: { _controller: TangaraCoreBundle:Project:upload }
    requirements:
        id:  \d+

tangara_project_edit:
    pattern:  /edit/{id}
    defaults: { _controller: TangaraCoreBundle:Project:edit }
    requirements:
        id:  \d+

tangara_project_create:
    pattern:  /create
    defaults: { _controller: TangaraCoreBundle:Project:create}

tangara_project_files:
    pattern:  /files
    defaults: { _controller: TangaraCoreBundle:File:getFiles }

tangara_project_test:
    pattern:  /test
    defaults: { _controller: TangaraCoreBundle:File:test }
 



