#infoAction: info about group of the user   
tangara_user_groupInfo:
    pattern:  /profil/group/{id}
    defaults: { _controller: TangaraCoreBundle:Group:infoGroup }
    
tangara_user_group_new:
    pattern:  /new
    defaults: { _controller: TangaraCoreBundle:Group:new }
    
tangara_group_acceptRequest:
    pattern:  /accept_request
    defaults: { _controller: TangaraCoreBundle:Group:acceptRequest }
    
tangara_group_refuseRequest:
    pattern:  /refuse_request
    defaults: { _controller: TangaraCoreBundle:Group:refuseRequest }
    
