#infoAction: info about group of the user   
tangara_user_group_info:
    path:  /profil/group/{id}
    defaults: { _controller: TangaraCoreBundle:Group:infoGroup }
    
tangara_user_group_new:
    path:  /new
    defaults: { _controller: TangaraCoreBundle:FOSGroup:new }
        
tangara_group_edit:
    path:  /group/edit/{groupName}
    defaults: { _controller: TangaraCoreBundle:FOSGroup:edit }
    
tangara_core_group_list:
    path:  /group/list
    defaults: { _controller: TangaraCoreBundle:Group:list }
    
tangara_core_group_new:
    path:  /group/new
    defaults: { _controller: TangaraCoreBundle:Group:new }

tangara_core_group_edit:
    path:  /group/edit
    defaults: { _controller: TangaraCoreBundle:Group:new } 
    
tangara_group_acceptRequest:
    path:  /accept_request
    defaults: { _controller: TangaraCoreBundle:Group:acceptRequest }
    
tangara_group_refuseRequest:
    path:  /refuse_request
    defaults: { _controller: TangaraCoreBundle:Group:refuseRequest }

tangara_group_remove_user:
    path:  /group/del_user
    defaults: { _controller: TangaraCoreBundle:Group:removeUser }
