#tangara_tangarajs_index:
#    pattern:  /
#    defaults: { _controller: TangaraCoreBundle:Project:index }

#tangara_tangarajs_groups:            
#    pattern:  /getGroups
#    defaults: { _controller: TangaraCoreBundle:Project:getGroups }

tangara_tangarajs_get_files:            
    pattern:  /getfiles/{cat}/{id}
    defaults: { _controller: TangaraCoreBundle:File:getFiles }
    requirements:
        cat: 1|2
        id:  \d+

tangara_tangarajs_get_resources:            
    pattern:  /getresources/{cat}/{id}
    defaults: { _controller: TangaraCoreBundle:File:getResources }
    requirements:
        cat: 1|2
        id:  \d+