#infoAction: info about group of the user   
tangara_user_group_info:
    pattern:  /profil/group/{id}
    defaults: { _controller: TangaraCoreBundle:Group:infoGroup }
    
tangara_user_group_new:
    pattern:  /new
    defaults: { _controller: TangaraCoreBundle:Group:new }
    
 
