tangara_core_ajax:
    path:  /
    defaults: { _controller: TangaraCoreBundle:Debug:ajax }
 
tangara_core_ajax_set_project_id:
    path:  /setprojectid/{project_id}
    defaults: { _controller: TangaraCoreBundle:Debug:setProjectId }
    requirements:
        project_id:  \d+
 