tangara_tangara_homepage:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Default:index }
    

tangara_project_ajax:
    pattern:  /ajax
    defaults: { _controller: TangaraCoreBundle:Default:ajax }

tangara_project_ajax_test:
    pattern:  /ajax/test
    defaults: { _controller: TangaraCoreBundle:File:removeFile }
    
    
    
#route de redirection
tangara_core_group_list:
    pattern:  /group/list
    defaults: { _controller: TangaraCoreBundle:Group:list }
    
tangara_core_group_new:
    pattern:  /group/new
    defaults: { _controller: TangaraCoreBundle:Group:new }

tangara_core_group_edit:
    pattern:  /group/edit
    defaults: { _controller: TangaraCoreBundle:Group:new }    
