tangara_tangara_homepage:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Default:index }
    
# join group confirmation
tangara_project_confirmation:
    pattern:  /confirmation
    defaults: { _controller: TangaraCoreBundle:Default:confirmation }
    
tangara_project_ajax:
    pattern:  /ajax
    defaults: { _controller: TangaraCoreBundle:Default:ajax }
