#infoAction: info about group of the user   
tangara_user_groupInfo:
    pattern:  /profil/group/{id}
    defaults: { _controller: TangaraCoreBundle:Group:infoGroup }
    
Tangara_user_group_new:
    pattern:  /new
    defaults: { _controller: TangaraCoreBundle:Group:new }
    
 