tangara_core_homepage:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Default:index }

tangara_core_ajax:
    pattern:  /ajax
    defaults: { _controller: TangaraCoreBundle:Default:ajax }

tangara_core_translation_test:
    pattern:  /translate
    defaults: { _controller: TangaraCoreBundle:Default:translation }
  
