tangara_tangarajs_index:
    pattern:  /
    defaults: { _controller: TangaraCoreBundle:Project:index }

tangara_tangarajs_groups:            
    pattern:  /getGroups
    defaults: { _controller: TangaraCoreBundle:Project:getGroups }

#tangara_tangarajs_projects:            
#    pattern:  /getProjects
#    defaults: { _controller: TangaraCoreBundle:Project:getProjects }
