parameters:
    tangara_core.uploader.class: Tangara\CoreBundle\Uploader\Uploader
    tangara_core.uploader.directory: C:\tangara
    tangara_core.tangarajs: C:\tangara
    
services:
    tangara_core.project_manager: 
        class: Tangara\CoreBundle\Manager\ProjectManager
        arguments: 
            - @doctrine.orm.entity_manager
            - %tangara_core.settings.directory.upload%
            - @security.context
    tangara_core.document_manager: 
        class: Tangara\CoreBundle\Manager\DocumentManager
        arguments: 
            - @doctrine.orm.entity_manager
            - @tangara_core.project_manager
    tangara_core.user_manager: 
        class: Tangara\CoreBundle\Manager\UserManager
        arguments: 
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
    tangara_core.settings:
        class: Tangara\CoreBundle\Entity\Document
    tangara_core.user_listener:
        class: Tangara\CoreBundle\EventListener\UserListener
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - @doctrine.orm.entity_manager
            - @session

