tangara_project_index:
    pattern:  /
    defaults: { _controller: TangaraProjectBundle:Default:index }

tangara_project_show:            
    pattern:  /show/{id}
    defaults: { _controller: TangaraProjectBundle:Default:show }
    requirements:
        id:  \d+
    
tangara_project_new:
    pattern:  /new
    defaults: { _controller: TangaraProjectBundle:Default:new }

tangara_project_list:
    pattern:  /list
    defaults: { _controller: TangaraProjectBundle:Default:list }

tangara_project_upload:
    pattern:  /upload
    defaults: { _controller: TangaraProjectBundle:Default:upload }

tangara_project_up:
    pattern:  /ud
    defaults: { _controller: TangaraProjectBundle:Default:up }

tangara_project_edit:
    pattern:  /edit/{id}
    defaults: { _controller: TangaraProjectBundle:Default:edit }
    requirements:
        id:  \d+

tangara_project_create:
    pattern:  /create
    defaults: { _controller: TangaraProjectBundle:Default:create}

tangara_project_files:
    pattern:  /files
    defaults: { _controller: TangaraProjectBundle:File:getFiles }

tangara_project_tgr_content:
    pattern:  /content
    defaults: { _controller: TangaraProjectBundle:File:getContent }
    
tangara_project_ajax:
    pattern:  /ajax
    defaults: { _controller: TangaraProjectBundle:Default:getAjax}
 
#controleur qui donne la page de confirmation   
tangara_project_confirmation:
    pattern:  /confirmation
    defaults: { _controller: TangaraProjectBundle:Default:confirmation }

#controleur qui donne la liste de tous les groupes
tangara_project_listgroup:
    pattern:  /listGroup
    defaults: { _controller: TangaraProjectBundle:Default:listGroup }

#controleur qui donne la liste de tous les projets    
tangara_project_listproject:
    pattern:  /listProjet
    defaults: { _controller: TangaraProjectBundle:Default:listProjet }

#controleur qui donne la liste de tous les groupes dont l'user n'est pas membre     
tangara_project_listnogroup:
    pattern:  /listNoGroup
    defaults: { _controller: TangaraProjectBundle:Default:listNoGroup }
