tangara_project_index:
    pattern:  /
    defaults: { _controller: TangaraProjectBundle:Default:index }

tangara_project_show:            
    pattern:  /show/{id}
    defaults: { _controller: TangaraProjectBundle:Default:show }
    requirements:
        id:  \d+
    
tangara_project_add:
    pattern:  /add
    defaults: { _controller: TangaraProjectBundle:Default:add }

tangara_project_upload:
    pattern:  /upload
    defaults: { _controller: TangaraProjectBundle:Default:upload }

tangara_project_edit:
    pattern:  /edit/{id}
    defaults: { _controller: TangaraProjectBundle:Default:edit }
    requirements:
        id:  \d+
