tangara_project_index:
    pattern:  /
    defaults: { _controller: TangaraProjectBundle:Default:index }
    
tangara_project_add:
    pattern:  /add
    defaults: { _controller: TangaraProjectBundle:Default:addProject }
