parameters:
#    tangara.project.example.class: Tangara\ProjectBundle\Example

services:
#    tangara.project.example:
#        class: %tangara_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

